
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BuscarDatos
{

using System;
    using System.Collections.Generic;
    
public partial class Clientes
{

    public int id { get; set; }

    public string nombre { get; set; }

    public string apellidop { get; set; }

    public string apellidom { get; set; }

    public string telefono { get; set; }

    public string direccion { get; set; }

    public string asesor { get; set; }

    public string fraccionamiento { get; set; }

    public string financiamiento { get; set; }

    public string estatus { get; set; }

    public string ultimo_seguimiento { get; set; }

    public string ver_expediente { get; set; }

}

}
